import { execFile } from 'node:child_process';
import { mkdir, mkdtemp, readFile, readdir, rm, stat, writeFile } from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import { promisify } from 'node:util';
import { describe, expect, it } from 'vitest';
import { installPack, listInstalledPacks, uninstallPack } from '../src/pack/installPack.js';
import { loadPack, loadPackManifest, normalizeManifest } from '../src/pack/loadPack.js';
import { readLockfile, renderLockfile, writeLockfile } from '../src/pack/lockfile.js';
import { addPackRegistryBlocks, PACK_BEGIN_PREFIX, PACK_END_PREFIX, removeBlocksForPack, removePackRegistryBlocks, renderPackRegistryBlock } from '../src/pack/registryRewrite.js';
import { describePackSource, parsePackSource } from '../src/pack/sources.js';
import { fetchPackToTempDir } from '../src/pack/fetcher.js';
import type { PackFetcher } from '../src/pack/fetcher.js';
import type { InstalledPack, LoadedPack, PackSource } from '../src/pack/types.js';

const execFileAsync = promisify(execFile);

async function writeFixturePack(dir: string, overrides: { manifest?: string; tools?: Record<string, string>; grammars?: Record<string, string>; templates?: Record<string, string> } = {}): Promise<void> {
  const manifest = overrides.manifest ?? defaultManifest();
  await mkdir(dir, { recursive: true });
  await writeFile(path.join(dir, 'utk.pack.toml'), manifest, 'utf8');
  const tools = overrides.tools ?? { 'tools/git.toml': defaultToolToml() };
  for (const [relative, content] of Object.entries(tools)) {
    const target = path.join(dir, relative);
    await mkdir(path.dirname(target), { recursive: true });
    await writeFile(target, content, 'utf8');
  }
  const grammars = overrides.grammars ?? { 'grammars/git/ref.lark': defaultLark() };
  for (const [relative, content] of Object.entries(grammars)) {
    const target = path.join(dir, relative);
    await mkdir(path.dirname(target), { recursive: true });
    await writeFile(target, content, 'utf8');
  }
  const templates = overrides.templates ?? { 'templates/git-checkout.template.ts': defaultTemplate() };
  for (const [relative, content] of Object.entries(templates)) {
    const target = path.join(dir, relative);
    await mkdir(path.dirname(target), { recursive: true });
    await writeFile(target, content, 'utf8');
  }
}

function defaultManifest(): string {
  return [
    '[pack]',
    'name = "git-cli"',
    'version = "1.2.0"',
    'description = "git tools"',
    'license = "Apache-2.0"',
    'authors = ["alice"]',
    'homepage = "https://example.com"',
    'keywords = ["git"]',
    '',
    '[compatibility]',
    'utk = ">=0.1.0"',
    'pack_spec = "2"',
    '',
    '[[tools]]',
    'id = "git"',
    'kind = "bash-like"',
    'output_cache = true',
    'bypass_on_cache = false',
    'curry_fields = ["subcommand"]',
    '',
    '[[grammars]]',
    'tool = "git"',
    'field = "ref"',
    'description = "branch/tag/sha"',
    '',
    '[[templates]]',
    'id = "git.checkout"',
    'file = "templates/git-checkout.template.ts"',
    'language = "typescript"',
    'tool = "git"',
    ''
  ].join('\n');
}

function defaultToolToml(): string {
  return [
    '[tool]',
    'id = "git"',
    'command = "git"',
    'description = "git CLI"',
    '',
    '[[parameters]]',
    'name = "subcommand"',
    'kind = "positional"',
    'completions = ["status", "log", "checkout"]',
    'required = true',
    ''
  ].join('\n');
}

function defaultLark(): string {
  return [
    '# generated by author',
    'start: REF',
    'REF: /[A-Za-z0-9_\\-\\/]{6,64}/',
    ''
  ].join('\n');
}

function defaultTemplate(): string {
  return [
    "import { defineTemplate, grammarSlot } from '@utk/core';",
    '',
    'export default defineTemplate({',
    "  id: 'git.checkout',",
    "  tool: 'git',",
    "  prompt: 'git checkout {{ref}}',",
    '  slots: {',
    "    ref: grammarSlot({ tool: 'git', field: 'ref' })",
    '  }',
    '});',
    ''
  ].join('\n');
}

describe('parsePackSource', () => {
  it('parses local paths', () => {
    expect(parsePackSource('./my-pack')).toEqual({ type: 'local', path: './my-pack' });
    expect(parsePackSource('/abs/path')).toEqual({ type: 'local', path: '/abs/path' });
    expect(parsePackSource('../sibling')).toEqual({ type: 'local', path: '../sibling' });
  });

  it('parses tarball paths and URLs', () => {
    expect(parsePackSource('./pack.tgz')).toEqual({ type: 'tarball', path: './pack.tgz' });
    expect(parsePackSource('https://example.com/pack.tar.gz')).toEqual({ type: 'tarball', path: 'https://example.com/pack.tar.gz' });
    expect(parsePackSource('pack.tgz')).toEqual({ type: 'tarball', path: 'pack.tgz' });
  });

  it('parses git short specs and full URLs', () => {
    expect(parsePackSource('github:alice/utk-pack-git')).toEqual({ type: 'git', url: 'https://github.com/alice/utk-pack-git' });
    expect(parsePackSource('github:alice/utk-pack-git#v1')).toEqual({ type: 'git', url: 'https://github.com/alice/utk-pack-git', ref: 'v1' });
    expect(parsePackSource('gitlab:alice/repo')).toEqual({ type: 'git', url: 'https://gitlab.com/alice/repo' });
    expect(parsePackSource('git+https://example.com/repo.git')).toEqual({ type: 'git', url: 'https://example.com/repo.git' });
    expect(parsePackSource('git+https://example.com/repo.git#main')).toEqual({ type: 'git', url: 'https://example.com/repo.git', ref: 'main' });
    expect(parsePackSource('git@example.com:repo.git')).toEqual({ type: 'git', url: 'git@example.com:repo.git' });
    expect(parsePackSource('https://example.com/repo')).toEqual({ type: 'git', url: 'https://example.com/repo' });
  });

  it('parses npm specs including scoped names', () => {
    expect(parsePackSource('utk-git-cli')).toEqual({ type: 'npm', spec: 'utk-git-cli' });
    expect(parsePackSource('@utk/git-cli')).toEqual({ type: 'npm', spec: '@utk/git-cli' });
    expect(parsePackSource('utk-git-cli@^1.0.0')).toEqual({ type: 'npm', spec: 'utk-git-cli@^1.0.0' });
  });

  it('rejects unrecognized and empty sources', () => {
    expect(() => parsePackSource('')).toThrow();
    expect(() => parsePackSource('   ')).toThrow();
    expect(() => parsePackSource('!!invalid')).toThrow();
    expect(() => parsePackSource('github:')).toThrow();
  });

  it('describes sources for logging', () => {
    expect(describePackSource({ type: 'local', path: './x' })).toBe('local:./x');
    expect(describePackSource({ type: 'tarball', path: 'p.tgz' })).toBe('tarball:p.tgz');
    expect(describePackSource({ type: 'git', url: 'https://example.com/r', ref: 'main' })).toBe('git:https://example.com/r#main');
    expect(describePackSource({ type: 'git', url: 'https://example.com/r' })).toBe('git:https://example.com/r');
    expect(describePackSource({ type: 'npm', spec: '@utk/x' })).toBe('npm:@utk/x');
  });

  it('rejects non-string inputs', () => {
    expect(() => parsePackSource(undefined as unknown as string)).toThrow();
  });
});

describe('loadPack boolean validation', () => {
  it('rejects non-boolean output_cache values from a pack manifest', async () => {
    const dir = await mkdtemp(path.join(os.tmpdir(), 'utk-loadpack-bool-'));
    await writeFixturePack(dir, {
      manifest: [
        '[pack]',
        'name = "demo"',
        'version = "1.0.0"',
        '',
        '[[tools]]',
        'id = "git"',
        'kind = "bash-like"',
        'output_cache = "yes"',
        ''
      ].join('\n')
    });
    const { loadPackManifest } = await import('../src/pack/loadPack.js');
    await expect(loadPackManifest(dir)).rejects.toThrow(/output_cache must be a boolean/);
  });

  it('falls through (no fallback to seed) when the lark file read fails with a non-ENOENT error', async () => {
    const dir = await mkdtemp(path.join(os.tmpdir(), 'utk-loadpack-lark-eacces-'));
    await writeFixturePack(dir, {
      manifest: [
        '[pack]',
        'name = "demo"',
        'version = "1.0.0"',
        '',
        '[[grammars]]',
        'tool = "git"',
        'field = "ref"',
        ''
      ].join('\n'),
      tools: {},
      grammars: { 'grammars/git/ref.lark': '' },
      templates: {}
    });
    // Make the lark a directory so readFile throws EISDIR (non-ENOENT).
    const { mkdir, rm } = await import('node:fs/promises');
    await rm(path.join(dir, 'grammars', 'git', 'ref.lark'));
    await mkdir(path.join(dir, 'grammars', 'git', 'ref.lark'));
    const { loadPack } = await import('../src/pack/loadPack.js');
    await expect(loadPack(dir)).rejects.toThrow();
  });
});

describe('loadPackManifest', () => {
  it('loads and normalizes a complete manifest', async () => {
    const dir = await mkdtemp(path.join(os.tmpdir(), 'utk-pack-manifest-'));
    await writeFixturePack(dir);
    const manifest = await loadPackManifest(dir);
    expect(manifest.pack.name).toBe('git-cli');
    expect(manifest.tools?.[0]?.id).toBe('git');
    expect(manifest.grammars?.[0]?.field).toBe('ref');
    expect(manifest.templates?.[0]?.language).toBe('typescript');
  });

  it('loads pack tools, grammars, and templates', async () => {
    const dir = await mkdtemp(path.join(os.tmpdir(), 'utk-pack-load-'));
    await writeFixturePack(dir);
    const pack = await loadPack(dir);
    expect(pack.tools).toHaveLength(1);
    expect(pack.grammars[0]?.lark).toContain('REF');
    expect(pack.grammars[0]?.larkHash).toMatch(/^[a-f0-9]+$/);
    expect(pack.templates[0]?.source).toContain('defineTemplate');
  });

  it('rejects a grammar entry without a .lark file', async () => {
    const dir = await mkdtemp(path.join(os.tmpdir(), 'utk-pack-missing-lark-'));
    const manifest = [
      '[pack]',
      'name = "x"',
      'version = "1.0.0"',
      '',
      '[[grammars]]',
      'tool = "git"',
      'field = "ref"',
      ''
    ].join('\n');
    await writeFixturePack(dir, { manifest, tools: {}, grammars: {}, templates: {} });
    await expect(loadPack(dir)).rejects.toThrow();
  });

  it('rejects a pack that declares a `seed` field on a grammar entry', async () => {
    const dir = await mkdtemp(path.join(os.tmpdir(), 'utk-pack-rejects-seed-'));
    const manifest = [
      '[pack]',
      'name = "x"',
      'version = "1.0.0"',
      '',
      '[[grammars]]',
      'tool = "git"',
      'field = "ref"',
      'seed = "grammars/git/ref.grammar.json"',
      ''
    ].join('\n');
    await writeFixturePack(dir, { manifest, tools: {}, grammars: {}, templates: {} });
    await expect(loadPackManifest(dir)).rejects.toThrow(/no longer supported/);
  });

  it('supports a JSON tool file via the file override', async () => {
    const dir = await mkdtemp(path.join(os.tmpdir(), 'utk-pack-json-tool-'));
    const manifest = [
      '[pack]',
      'name = "x"',
      'version = "1.0.0"',
      '',
      '[[tools]]',
      'id = "git"',
      'kind = "bash-like"',
      'file = "tools/git.json"',
      ''
    ].join('\n');
    await writeFixturePack(dir, {
      manifest,
      tools: { 'tools/git.json': JSON.stringify({ tool: { id: 'git', command: 'git' }, parameters: [] }) },
      grammars: {},
      templates: {}
    });
    const pack = await loadPack(dir);
    expect(pack.tools[0]?.source.tool).toBeDefined();
  });

  it('reads explicit lark paths and supports structured tools', async () => {
    const dir = await mkdtemp(path.join(os.tmpdir(), 'utk-pack-explicit-lark-'));
    const manifest = [
      '[pack]',
      'name = "code-search"',
      'version = "1.0.0"',
      '',
      '[[tools]]',
      'id = "tool.code.search"',
      'kind = "structured"',
      '',
      '[[grammars]]',
      'tool = "tool.code.search"',
      'field = "query"',
      'lark = "grammars/explicit.lark"',
      ''
    ].join('\n');
    await writeFixturePack(dir, {
      manifest,
      tools: { 'tools/tool.code.search.toml': '[tool]\nid = "tool.code.search"\n' },
      grammars: {
        'grammars/explicit.lark': 'start: Q\nQ: /[A-Za-z]+/\n'
      },
      templates: {}
    });
    const pack = await loadPack(dir);
    expect(pack.grammars[0]?.lark).toContain('Q: /[A-Za-z]+/');
    expect(pack.grammars[0]?.larkHash).toMatch(/^[a-f0-9]+$/);
  });

  it('rejects invalid manifest shapes', () => {
    expect(() => normalizeManifest({ pack: 'oops' as unknown as Record<string, unknown> })).toThrow();
    expect(() => normalizeManifest({ pack: { name: 'invalid name!', version: '1.0.0' } })).toThrow(/Invalid pack name/);
    expect(() => normalizeManifest({ pack: { name: 'ok', version: 'bad' } })).toThrow(/Invalid pack version/);
    expect(() => normalizeManifest({ pack: { name: 'ok', version: '1.0.0' }, tools: 'oops' as unknown as unknown[] })).toThrow();
    expect(() =>
      normalizeManifest({
        pack: { name: 'ok', version: '1.0.0' },
        templates: [{ id: 't', file: 't.ts', language: 'ruby' }]
      })
    ).toThrow(/language must be/);
    expect(() =>
      normalizeManifest({
        pack: { name: 'ok', version: '1.0.0' },
        tools: [{ id: 'x', kind: 'lisp' }]
      })
    ).toThrow(/kind must be/);
    expect(() => normalizeManifest({ pack: { name: '', version: '1.0.0' } })).toThrow(/must be a non-empty string/);
    expect(() =>
      normalizeManifest({ pack: { name: 'ok', version: '1.0.0', authors: ['ok', 42] as unknown as string[] } })
    ).toThrow(/array of strings/);
  });

  it('accepts partial compatibility tables', () => {
    const onlyUtk = normalizeManifest({ pack: { name: 'ok', version: '1.0.0' }, compatibility: { utk: '>=0.1.0' } });
    expect(onlyUtk.compatibility?.utk).toBe('>=0.1.0');
    expect(onlyUtk.compatibility?.pack_spec).toBeUndefined();
    const onlySpec = normalizeManifest({ pack: { name: 'ok', version: '1.0.0' }, compatibility: { pack_spec: '1' } });
    expect(onlySpec.compatibility?.pack_spec).toBe('1');
    const empty = normalizeManifest({ pack: { name: 'ok', version: '1.0.0' }, compatibility: {} });
    expect(empty.compatibility).toEqual({});
  });

  it('round-trips optional manifest fields', () => {
    const manifest = normalizeManifest({
      pack: {
        name: 'ok',
        version: '1.0.0',
        description: 'd',
        license: 'MIT',
        authors: ['a'],
        homepage: 'h',
        keywords: ['k']
      },
      compatibility: { utk: '>=0.1.0', pack_spec: '1' },
      tools: [{ id: 't', kind: 'structured', file: 'x.toml', output_cache: true, bypass_on_cache: true, curry_fields: ['a'] }],
      grammars: [{ tool: 't', field: 'f', description: 'd' }],
      templates: [{ id: 'x', file: 'x.ts', language: 'python', tool: 't' }]
    });
    expect(manifest.compatibility?.utk).toBe('>=0.1.0');
    expect(manifest.tools?.[0]?.output_cache).toBe(true);
    expect(manifest.tools?.[0]?.curry_fields).toEqual(['a']);
    expect(manifest.grammars?.[0]?.description).toBe('d');
    expect(manifest.templates?.[0]?.language).toBe('python');
  });
});

describe('removeBlocksForPack unterminated', () => {
  it('throws when a begin marker has no matching end', async () => {
    const { removeBlocksForPack } = await import('../src/pack/registryRewrite.js');
    const orphan = '[serialization]\ndefault = "toon"\n\n# utk-pack-begin: ghost\n[[tools.registry]]\ntool = "x"\n';
    expect(() => removeBlocksForPack(orphan, 'ghost')).toThrow(/has no matching/);
  });
});

describe('registryRewrite', () => {
  it('renders, adds, and removes pack blocks idempotently', async () => {
    const workspace = await mkdtemp(path.join(os.tmpdir(), 'utk-registry-'));
    const pack: LoadedPack = makeLoadedPack();
    await addPackRegistryBlocks(workspace, 'git-cli', pack.tools);
    let text = await readFile(path.join(workspace, '.utk', 'config.toml'), 'utf8');
    expect(text).toContain(`${PACK_BEGIN_PREFIX} git-cli`);
    expect(text).toContain(`${PACK_END_PREFIX} git-cli`);
    expect(text).toContain('[[tools.registry]]');
    expect(text).toContain('[[tools.registry.structured_fields]]');
    await addPackRegistryBlocks(workspace, 'git-cli', pack.tools);
    text = await readFile(path.join(workspace, '.utk', 'config.toml'), 'utf8');
    expect(text.match(/utk-pack-begin: git-cli/g)).toHaveLength(1);
    await removePackRegistryBlocks(workspace, 'git-cli');
    text = await readFile(path.join(workspace, '.utk', 'config.toml'), 'utf8');
    expect(text).not.toContain('utk-pack');
  });

  it('rendering omits structured fields when none and falls back when tool source has no .tool table', () => {
    const block = renderPackRegistryBlock('p', {
      entry: { id: 'foo', kind: 'bash-like' },
      source: { description: 'flat', parameters: 'nope' as unknown as unknown[] }
    });
    expect(block).toContain('tool = "foo"');
    expect(block).toContain('description = "flat"');
    expect(block).not.toContain('structured_fields');
  });

  it('strips required and description fields when omitted', () => {
    const block = renderPackRegistryBlock('p', {
      entry: { id: 'foo', kind: 'structured' },
      source: { tool: {}, parameters: [{ name: 'a', completions: ['x'] }, { invalid: true }] }
    });
    expect(block).toContain('completions = ["x"]');
  });

  it('skips non-object and unnamed parameter entries', () => {
    const block = renderPackRegistryBlock('p', {
      entry: { id: 'foo', kind: 'structured' },
      source: {
        tool: {},
        parameters: [null, 'oops', { name: 'real', completions: 'not-array' as unknown as string[], required: true, description: 'rd' }]
      }
    });
    expect(block).toContain('name = "real"');
    expect(block).toContain('completions = []');
    expect(block).toContain('required = true');
    expect(block).toContain('description = "rd"');
  });

  it('handles trailing newline in pre-existing config without duplicating', async () => {
    const workspace = await mkdtemp(path.join(os.tmpdir(), 'utk-registry-nl-'));
    await mkdir(path.join(workspace, '.utk'), { recursive: true });
    await writeFile(path.join(workspace, '.utk', 'config.toml'), '', 'utf8');
    const pack = makeLoadedPack();
    await addPackRegistryBlocks(workspace, 'git-cli', pack.tools);
    const text = await readFile(path.join(workspace, '.utk', 'config.toml'), 'utf8');
    expect(text).toContain('utk-pack-begin: git-cli');
  });

  it('adds a trailing newline when the existing config lacks one', async () => {
    const workspace = await mkdtemp(path.join(os.tmpdir(), 'utk-registry-no-nl-'));
    await mkdir(path.join(workspace, '.utk'), { recursive: true });
    await writeFile(path.join(workspace, '.utk', 'config.toml'), '[serialization]\ndefault = "toon"', 'utf8');
    const pack = makeLoadedPack();
    await addPackRegistryBlocks(workspace, 'git-cli', pack.tools);
    const text = await readFile(path.join(workspace, '.utk', 'config.toml'), 'utf8');
    expect(text).toContain('[serialization]\ndefault = "toon"\n');
    expect(text).toContain('utk-pack-begin: git-cli');
  });

  it('removeBlocksForPack tolerates missing markers', () => {
    expect(removeBlocksForPack('[serialization]\ndefault = "toon"\n', 'absent')).toContain('[serialization]');
  });
});

describe('lockfile', () => {
  it('propagates non-ENOENT lockfile read failures', async () => {
    const workspace = await mkdtemp(path.join(os.tmpdir(), 'utk-lockfile-eacces-'));
    const { mkdir } = await import('node:fs/promises');
    await mkdir(path.join(workspace, '.utk', 'packs.lock.toml'), { recursive: true });
    const { readLockfile } = await import('../src/pack/lockfile.js');
    await expect(readLockfile(workspace)).rejects.toThrow();
  });

  it('rejects an incompatible spec version', async () => {
    const workspace = await mkdtemp(path.join(os.tmpdir(), 'utk-lockfile-spec-'));
    const { mkdir, writeFile } = await import('node:fs/promises');
    await mkdir(path.join(workspace, '.utk'), { recursive: true });
    await writeFile(path.join(workspace, '.utk', 'packs.lock.toml'), 'spec = "999"\n', 'utf8');
    const { readLockfile } = await import('../src/pack/lockfile.js');
    await expect(readLockfile(workspace)).rejects.toThrow(/packs\.lock\.toml spec 999 is incompatible/);
  });

  it('renders and reads a populated lockfile', async () => {
    const workspace = await mkdtemp(path.join(os.tmpdir(), 'utk-lockfile-'));
    const pack: InstalledPack = {
      name: 'git-cli',
      version: '1.0.0',
      source: 'local:./fixture',
      revision: 'abc',
      contentHash: 'hash',
      installedAt: '2026-05-19T20:00:00Z',
      tools: ['git'],
      templates: ['git.checkout'],
      grammars: [
        { tool: 'git', field: 'ref', larkHash: 'h1' },
        { tool: 'git', field: 'remote', larkHash: 'h3' }
      ]
    };
    await writeLockfile(workspace, [pack]);
    const round = await readLockfile(workspace);
    expect(round).toHaveLength(1);
    expect(round[0]?.name).toBe('git-cli');
    expect(round[0]?.grammars[0]?.larkHash).toBe('h1');
    expect(round[0]?.grammars[1]?.larkHash).toBe('h3');
  });

  it('returns an empty list when the lockfile is missing', async () => {
    const workspace = await mkdtemp(path.join(os.tmpdir(), 'utk-lockfile-missing-'));
    const packs = await readLockfile(workspace);
    expect(packs).toEqual([]);
  });

  it('rejects malformed lockfile entries', async () => {
    const workspace = await mkdtemp(path.join(os.tmpdir(), 'utk-lockfile-bad-'));
    await mkdir(path.join(workspace, '.utk'), { recursive: true });
    await writeFile(path.join(workspace, '.utk', 'packs.lock.toml'), 'spec = "2"\n\n[[packs]]\nname = 42\n', 'utf8');
    await expect(readLockfile(workspace)).rejects.toThrow();
  });

  it('rejects non-table pack entries', async () => {
    const workspace = await mkdtemp(path.join(os.tmpdir(), 'utk-lockfile-nontable-'));
    await mkdir(path.join(workspace, '.utk'), { recursive: true });
    await writeFile(path.join(workspace, '.utk', 'packs.lock.toml'), 'spec = "2"\npacks = ["broken"]\n', 'utf8');
    await expect(readLockfile(workspace)).rejects.toThrow(/must be a table/);
  });

  it('rejects non-table grammars entries', async () => {
    const workspace = await mkdtemp(path.join(os.tmpdir(), 'utk-lockfile-bad-grammar-'));
    await mkdir(path.join(workspace, '.utk'), { recursive: true });
    await writeFile(
      path.join(workspace, '.utk', 'packs.lock.toml'),
      [
        'spec = "2"',
        '',
        '[[packs]]',
        'name = "p"',
        'version = "1.0.0"',
        'source = "s"',
        'revision = "r"',
        'content_hash = "h"',
        'installed_at = "t"',
        'grammars = ["broken"]',
        ''
      ].join('\n'),
      'utf8'
    );
    await expect(readLockfile(workspace)).rejects.toThrow(/grammars entry must be a table/);
  });

  it('renders empty pack lists', () => {
    expect(renderLockfile([])).toContain('spec = "2"');
  });

  it('handles arrays missing optional fields gracefully', async () => {
    const workspace = await mkdtemp(path.join(os.tmpdir(), 'utk-lockfile-sparse-'));
    await mkdir(path.join(workspace, '.utk'), { recursive: true });
    await writeFile(
      path.join(workspace, '.utk', 'packs.lock.toml'),
      [
        'spec = "2"',
        '',
        '[[packs]]',
        'name = "p"',
        'version = "1.0.0"',
        'source = "local"',
        'revision = "r"',
        'content_hash = "h"',
        'installed_at = "t"',
        ''
      ].join('\n'),
      'utf8'
    );
    const round = await readLockfile(workspace);
    expect(round[0]?.tools).toEqual([]);
    expect(round[0]?.templates).toEqual([]);
    expect(round[0]?.grammars).toEqual([]);
  });
});

describe('fetcher', () => {
  it('copies a local pack directory', async () => {
    const source = await mkdtemp(path.join(os.tmpdir(), 'utk-fetch-src-'));
    await writeFixturePack(source);
    const workspace = await mkdtemp(path.join(os.tmpdir(), 'utk-fetch-ws-'));
    const fetched = await fetchPackToTempDir({ type: 'local', path: source }, workspace);
    const manifest = await readFile(path.join(fetched.dir, 'utk.pack.toml'), 'utf8');
    expect(manifest).toContain('git-cli');
    expect(fetched.revision).toContain('local:');
  });

  it('rejects non-directory local sources', async () => {
    const tempDir = await mkdtemp(path.join(os.tmpdir(), 'utk-fetch-bad-local-'));
    const filePath = path.join(tempDir, 'not-a-dir.txt');
    await writeFile(filePath, 'x', 'utf8');
    await expect(fetchPackToTempDir({ type: 'local', path: filePath }, tempDir)).rejects.toThrow(/must be a directory/);
  });

  it('extracts a tarball into a temp dir', async () => {
    const source = await mkdtemp(path.join(os.tmpdir(), 'utk-fetch-tar-src-'));
    await writeFixturePack(path.join(source, 'pack'));
    const tarballPath = path.join(source, 'pack.tgz');
    await execFileAsync('tar', ['-czf', tarballPath, '-C', source, 'pack']);
    const workspace = await mkdtemp(path.join(os.tmpdir(), 'utk-fetch-tar-ws-'));
    const fetched = await fetchPackToTempDir({ type: 'tarball', path: tarballPath }, workspace);
    const manifest = await readFile(path.join(fetched.dir, 'utk.pack.toml'), 'utf8');
    expect(manifest).toContain('git-cli');
  });

  it('extracts a flat tarball (no top-level folder)', async () => {
    const source = await mkdtemp(path.join(os.tmpdir(), 'utk-fetch-flat-src-'));
    await writeFixturePack(source);
    const tarballPath = path.join(path.dirname(source), 'flat.tgz');
    await execFileAsync('tar', ['-czf', tarballPath, '-C', source, '.']);
    const workspace = await mkdtemp(path.join(os.tmpdir(), 'utk-fetch-flat-ws-'));
    const fetched = await fetchPackToTempDir({ type: 'tarball', path: tarballPath }, workspace);
    await stat(path.join(fetched.dir, 'utk.pack.toml'));
  });

  it('rejects non-file tarball sources', async () => {
    const tempDir = await mkdtemp(path.join(os.tmpdir(), 'utk-fetch-bad-tar-'));
    await expect(fetchPackToTempDir({ type: 'tarball', path: tempDir }, tempDir)).rejects.toThrow(/must be a file/);
  });

  it('handles tarballs whose single root entry is a file', async () => {
    const source = await mkdtemp(path.join(os.tmpdir(), 'utk-fetch-file-only-src-'));
    await writeFile(path.join(source, 'lonely.txt'), 'hi', 'utf8');
    const tarballPath = path.join(path.dirname(source), 'lonely.tgz');
    await execFileAsync('tar', ['-czf', tarballPath, '-C', source, 'lonely.txt']);
    const workspace = await mkdtemp(path.join(os.tmpdir(), 'utk-fetch-file-only-ws-'));
    const fetched = await fetchPackToTempDir({ type: 'tarball', path: tarballPath }, workspace);
    const list = await readdir(fetched.dir);
    expect(list).toContain('lonely.txt');
  });
});

describe('installPack / uninstallPack / listInstalledPacks', () => {
  it('installs from a local pack and merges all artifacts', async () => {
    const source = await mkdtemp(path.join(os.tmpdir(), 'utk-install-src-'));
    await writeFixturePack(source);
    const workspace = await mkdtemp(path.join(os.tmpdir(), 'utk-install-ws-'));
    const installed = await installPack(workspace, { type: 'local', path: source }, {
      now: () => new Date('2026-05-19T20:00:00Z')
    });
    expect(installed.name).toBe('git-cli');
    expect(installed.installedAt).toBe('2026-05-19T20:00:00.000Z');

    const config = await readFile(path.join(workspace, '.utk', 'config.toml'), 'utf8');
    expect(config).toContain('utk-pack-begin: git-cli');
    expect(config).toContain('tool = "git"');

    const lark = await readFile(path.join(workspace, '.utk', 'tools', 'git', 'fields', 'ref.lark'), 'utf8');
    expect(lark).toContain('REF');

    // .grammar.json must never be written under .utk/ — lark is the only persisted format.
    const fieldsDir = path.join(workspace, '.utk', 'tools', 'git', 'fields');
    const fieldFiles = await readdir(fieldsDir);
    expect(fieldFiles.every((name) => !name.endsWith('.grammar.json'))).toBe(true);

    const list = await listInstalledPacks(workspace);
    expect(list).toHaveLength(1);
    expect(list[0]?.name).toBe('git-cli');
  });

  it('preserves the previous lockfile when install fails (lockfile-last invariant)', async () => {
    // Install a pack successfully first.
    const source1 = await mkdtemp(path.join(os.tmpdir(), 'utk-atomic-src1-'));
    await writeFixturePack(source1);
    const workspace = await mkdtemp(path.join(os.tmpdir(), 'utk-atomic-ws-'));
    await installPack(workspace, { type: 'local', path: source1 });
    const lockBefore = await import('node:fs/promises').then((fs) => fs.readFile(path.join(workspace, '.utk', 'packs.lock.toml'), 'utf8'));
    expect(lockBefore).toContain('git-cli');

    // Stage a second install that will fail mid-way (config.toml turned into a directory).
    const source2 = await mkdtemp(path.join(os.tmpdir(), 'utk-atomic-src2-'));
    await writeFixturePack(source2, {
      manifest: '[pack]\nname = "other-pack"\nversion = "1.0.0"\ndescription = "x"\nlicense = "MIT"\n[compatibility]\nutk = "^0.1"\n'
    });
    await import('node:fs/promises').then(async (fs) => {
      await fs.rm(path.join(workspace, '.utk', 'config.toml'), { force: true });
      await fs.mkdir(path.join(workspace, '.utk', 'config.toml'), { recursive: true });
    });
    await expect(installPack(workspace, { type: 'local', path: source2 }, { skipLint: true })).rejects.toThrow();

    // The lockfile must still report the original pack only — no torn write, no half-applied state.
    const lockAfter = await import('node:fs/promises').then((fs) => fs.readFile(path.join(workspace, '.utk', 'packs.lock.toml'), 'utf8'));
    expect(lockAfter).toBe(lockBefore);
    expect(lockAfter).not.toContain('other-pack');
  });

  it('rejects remote tarball URLs from the built-in fetcher', async () => {
    const { fetchPackToTempDir } = await import('../src/pack/fetcher.js');
    await expect(fetchPackToTempDir({ type: 'tarball', path: 'https://example.com/pack.tgz' }, os.tmpdir())).rejects.toThrow(/Remote tarball URLs are not supported/);
  });

  it('rolls back grammars with no seed (covers undefined-observations branch)', async () => {
    const source = await mkdtemp(path.join(os.tmpdir(), 'utk-install-noseed-src-'));
    await writeFixturePack(source, {
      // grammar declared but no .grammar.json seed file
      grammars: { 'grammars/git/ref.lark': 'start: VALUE\nVALUE: /[A-Za-z]+/\n' }
    });
    const workspace = await mkdtemp(path.join(os.tmpdir(), 'utk-install-noseed-ws-'));
    await import('node:fs/promises').then((fs) => fs.mkdir(path.join(workspace, '.utk', 'config.toml'), { recursive: true }));
    await expect(installPack(workspace, { type: 'local', path: source })).rejects.toThrow();
    const exists = await import('node:fs/promises').then(async (fs) => {
      try { await fs.stat(path.join(workspace, '.utk', 'packs', 'git-cli')); return true; } catch { return false; }
    });
    expect(exists).toBe(false);
  });

  it('rolls back even when an individual rollback step fails', async () => {
    // Pre-create cache file as a directory so the templates-cache cleanup step throws.
    // The other rollback steps must still run so .utk/packs/<name> is removed.
    const source = await mkdtemp(path.join(os.tmpdir(), 'utk-install-rollback-partial-src-'));
    await writeFixturePack(source);
    const workspace = await mkdtemp(path.join(os.tmpdir(), 'utk-install-rollback-partial-ws-'));
    const { mkdir } = await import('node:fs/promises');
    await mkdir(path.join(workspace, '.utk', 'cache', 'templates', 'git-cli.json'), { recursive: true });
    await mkdir(path.join(workspace, '.utk', 'config.toml'), { recursive: true });
    await expect(installPack(workspace, { type: 'local', path: source })).rejects.toThrow();
    const exists = await import('node:fs/promises').then(async (fs) => {
      try { await fs.stat(path.join(workspace, '.utk', 'packs', 'git-cli')); return true; } catch { return false; }
    });
    expect(exists).toBe(false);
  });

  it('rolls back partial install state when a downstream step fails', async () => {
    const source = await mkdtemp(path.join(os.tmpdir(), 'utk-install-rollback-src-'));
    await writeFixturePack(source);
    const workspace = await mkdtemp(path.join(os.tmpdir(), 'utk-install-rollback-ws-'));
    // Pre-create config.toml as a directory so addPackRegistryBlocks' writeFile throws.
    await import('node:fs/promises').then((fs) => fs.mkdir(path.join(workspace, '.utk', 'config.toml'), { recursive: true }));
    await expect(installPack(workspace, { type: 'local', path: source })).rejects.toThrow();
    // Pack directory and template cache must have been rolled back.
    const exists = await import('node:fs/promises').then(async (fs) => {
      try { await fs.stat(path.join(workspace, '.utk', 'packs', 'git-cli')); return true; } catch { return false; }
    });
    expect(exists).toBe(false);
  });

  it('refuses to install a pack whose name contains path-traversal segments', async () => {
    const source = await mkdtemp(path.join(os.tmpdir(), 'utk-install-traversal-src-'));
    await writeFixturePack(source, {
      manifest: '[pack]\nname = "../escapee"\nversion = "1.0.0"\n'
    });
    const workspace = await mkdtemp(path.join(os.tmpdir(), 'utk-install-traversal-ws-'));
    await expect(installPack(workspace, { type: 'local', path: source }, { skipLint: true })).rejects.toThrow(/Path traversal/);
  });

  it('reinstalls with force and removes prior artifacts', async () => {
    const source = await mkdtemp(path.join(os.tmpdir(), 'utk-install-force-src-'));
    await writeFixturePack(source);
    const workspace = await mkdtemp(path.join(os.tmpdir(), 'utk-install-force-ws-'));
    await installPack(workspace, { type: 'local', path: source });
    await expect(installPack(workspace, { type: 'local', path: source })).rejects.toThrow(/already installed/);
    const reinstalled = await installPack(workspace, { type: 'local', path: source }, { force: true });
    expect(reinstalled.name).toBe('git-cli');
    const config = await readFile(path.join(workspace, '.utk', 'config.toml'), 'utf8');
    expect(config.match(/utk-pack-begin: git-cli/g)).toHaveLength(1);
  });

  it('uninstalls and reverses all on-disk effects', async () => {
    const source = await mkdtemp(path.join(os.tmpdir(), 'utk-uninstall-src-'));
    await writeFixturePack(source);
    const workspace = await mkdtemp(path.join(os.tmpdir(), 'utk-uninstall-ws-'));
    await installPack(workspace, { type: 'local', path: source });
    await uninstallPack(workspace, 'git-cli');
    const config = await readFile(path.join(workspace, '.utk', 'config.toml'), 'utf8');
    expect(config).not.toContain('utk-pack-begin');
    const list = await listInstalledPacks(workspace);
    expect(list).toEqual([]);
    const remaining = await readdir(path.join(workspace, '.utk', 'packs')).catch(() => [] as string[]);
    expect(remaining).not.toContain('git-cli');
  });

  it('throws when uninstalling an unknown pack', async () => {
    const workspace = await mkdtemp(path.join(os.tmpdir(), 'utk-uninstall-missing-'));
    await expect(uninstallPack(workspace, 'absent')).rejects.toThrow(/not installed/);
  });

  it('removes the .lark artifact during uninstall and writes no .grammar.json on install', async () => {
    const source = await mkdtemp(path.join(os.tmpdir(), 'utk-uninstall-lark-src-'));
    await writeFixturePack(source);
    const workspace = await mkdtemp(path.join(os.tmpdir(), 'utk-uninstall-lark-ws-'));
    await installPack(workspace, { type: 'local', path: source });
    // Walk the workspace and assert no .grammar.json files exist.
    async function findGrammarJson(dir: string): Promise<string[]> {
      const out: string[] = [];
      const stack = [dir];
      while (stack.length > 0) {
        const current = stack.pop()!;
        const entries = await readdir(current, { withFileTypes: true });
        for (const entry of entries) {
          const full = path.join(current, entry.name);
          if (entry.isDirectory()) stack.push(full);
          else if (entry.name.endsWith('.grammar.json')) out.push(full);
        }
      }
      return out;
    }
    expect(await findGrammarJson(path.join(workspace, '.utk'))).toEqual([]);
    await uninstallPack(workspace, 'git-cli');
    await expect(stat(path.join(workspace, '.utk', 'tools', 'git', 'fields', 'ref.lark'))).rejects.toThrow();
    const list = await listInstalledPacks(workspace);
    expect(list).toEqual([]);
  });

  it('removes lark artifact even when seed observations are zero', async () => {
    const source = await mkdtemp(path.join(os.tmpdir(), 'utk-uninstall-nogrammar-src-'));
    await writeFixturePack(source, {
      manifest: [
        '[pack]',
        'name = "no-seed"',
        'version = "1.0.0"',
        '',
        '[[grammars]]',
        'tool = "git"',
        'field = "ref"',
        ''
      ].join('\n'),
      tools: {},
      grammars: { 'grammars/git/ref.lark': defaultLark() },
      templates: {}
    });
    const workspace = await mkdtemp(path.join(os.tmpdir(), 'utk-uninstall-nogrammar-ws-'));
    await installPack(workspace, { type: 'local', path: source });
    await uninstallPack(workspace, 'no-seed');
    await expect(stat(path.join(workspace, '.utk', 'tools', 'git', 'fields', 'ref.lark'))).rejects.toThrow();
  });

  it('caches template descriptors when templates are present', async () => {
    const source = await mkdtemp(path.join(os.tmpdir(), 'utk-install-tpl-src-'));
    await writeFixturePack(source);
    const workspace = await mkdtemp(path.join(os.tmpdir(), 'utk-install-tpl-ws-'));
    await installPack(workspace, { type: 'local', path: source });
    const cachePath = path.join(workspace, '.utk', 'cache', 'templates', 'git-cli.json');
    const cached = JSON.parse(await readFile(cachePath, 'utf8')) as { templates: Array<{ id: string }> };
    expect(cached.templates[0]?.id).toBe('git.checkout');
  });

  it('skips lint when skipLint is set', async () => {
    const source = await mkdtemp(path.join(os.tmpdir(), 'utk-install-skiplint-src-'));
    await mkdir(source, { recursive: true });
    await mkdir(path.join(source, 'tools'), { recursive: true });
    await writeFile(
      path.join(source, 'utk.pack.toml'),
      [
        '[pack]',
        'name = "broken"',
        'version = "1.0.0"',
        '',
        '[[tools]]',
        'id = "git"',
        'kind = "bash-like"',
        ''
      ].join('\n'),
      'utf8'
    );
    await writeFile(path.join(source, 'tools', 'git.toml'), '[tool]\nid = "git"\n', 'utf8');
    const workspace = await mkdtemp(path.join(os.tmpdir(), 'utk-install-skiplint-ws-'));
    await expect(installPack(workspace, { type: 'local', path: source })).rejects.toThrow(/lint/i);
    const installed = await installPack(workspace, { type: 'local', path: source }, { skipLint: true });
    expect(installed.name).toBe('broken');
  });

  it('accepts an injected fetcher to install from non-local sources', async () => {
    const stage = await mkdtemp(path.join(os.tmpdir(), 'utk-fake-fetcher-src-'));
    await writeFixturePack(stage);
    const workspace = await mkdtemp(path.join(os.tmpdir(), 'utk-fake-fetcher-ws-'));
    const fakeFetcher: PackFetcher = async () => ({ dir: stage, revision: 'sha:deadbeef' });
    const installed = await installPack(workspace, { type: 'git', url: 'https://example.com/git-cli' }, { fetcher: fakeFetcher });
    expect(installed.revision).toBe('sha:deadbeef');
    expect(installed.source).toContain('git:https://example.com/git-cli');
  });
});

function makeLoadedPack(): LoadedPack {
  return {
    manifest: {
      pack: { name: 'git-cli', version: '1.0.0' }
    },
    rootDir: '/tmp/fake',
    tools: [
      {
        entry: { id: 'git', kind: 'bash-like', output_cache: true, bypass_on_cache: false, curry_fields: ['subcommand'] },
        source: {
          tool: { id: 'git', command: 'git', description: 'git CLI' },
          parameters: [{ name: 'subcommand', completions: ['status'], required: true, description: 'git subcommand' }]
        }
      }
    ],
    grammars: [],
    templates: []
  };
}
