import type { FieldGrammar } from './fieldGrammar.js';

export const COMPILE_LARK_VERSION = 1;

export function compileLark(grammar: FieldGrammar, options?: { ruleName?: string }): string {
  const ruleName = options?.ruleName ?? 'VALUE';
  const min = Math.max(1, grammar.lengthRange.min);
  const max = Math.max(min, grammar.lengthRange.max);
  const observedSeparators = Object.keys(grammar.separators)
    .filter((char) => {
      const stats = grammar.separators[char];
      return Boolean(stats && (stats.tight > 0 || stats.loose > 0));
    })
    .sort();
  const escapedSeparators = observedSeparators.map(escapeRegexChar).join('');
  // Allow spaces — observed field values frequently include multi-token forms.
  const charClass = `[A-Za-z0-9 ${escapedSeparators}]`;
  const lengthSpec = min === max ? `{${min}}` : `{${min},${max}}`;
  const lines = [
    `# generated by @utk/core compileLark v${COMPILE_LARK_VERSION}`,
    `# observations: ${grammar.observations}`,
    'start: ' + ruleName,
    `${ruleName}: /${charClass}${lengthSpec}/`
  ];
  return `${lines.join('\n')}\n`;
}

function escapeRegexChar(char: string): string {
  if (/[A-Za-z0-9]/.test(char)) return char;
  if (char === ']' || char === '\\' || char === '^' || char === '-' || char === '/') {
    return `\\${char}`;
  }
  return char;
}
